// css-neon — Neon light Web Component
// Generated by build/bundle.js on 2026-05-08
//
// Usage:  <script type="module" src="css-neon.js"></script>
//   or:   import { NeonLight, define } from "./css-neon.js";

/* ===== src/utils.js ===== */
const SVG_NS = 'http://www.w3.org/2000/svg';

function createSvgElement(tag, attrs = {}) {
  const el = document.createElementNS(SVG_NS, tag);
  for (const [key, value] of Object.entries(attrs)) {
    el.setAttribute(key, value);
  }
  return el;
}

function setAttrs(el, attrs = {}) {
  for (const [key, value] of Object.entries(attrs)) {
    el.setAttribute(key, value);
  }
}

function parseNumber(value, fallback) {
  const n = parseFloat(value);
  return Number.isNaN(n) ? fallback : n;
}

function parseBoolean(value) {
  if (typeof value === 'boolean') return value;
  return value !== null && value !== undefined && value !== 'false';
}

/* ===== src/config.js ===== */
const DEFAULTS = {
  color: '#ff69b4',
  glow: 10,
  blur: 4,
  animate: 'none',
  speed: 1,
  dashed: false,
  fontFamily: 'inherit',
  fontSize: 64,
  fontWeight: 'normal',
  fontStyle: 'normal',
  textTransform: 'none',
  letterSpacing: 0,
  svgStrokeWidth: 10,
  brokenRatio: 0.5,
};

// Attributes that trigger re-render on change
const OBSERVED_ATTRS = [
  'color', 'glow', 'blur', 'animate', 'speed', 'dashed',
  'text-color', 'text-glow', 'text-blur', 'text-animate', 'text-speed', 'text-dashed',
  'svg-color', 'svg-glow', 'svg-blur', 'svg-animate', 'svg-speed', 'svg-dashed', 'svg-stroke-width', 'svg-broken-ratio',
  'broken-ratio', 'path-config',
  'font-family', 'font-size', 'font-weight', 'font-style', 'text-transform', 'letter-spacing',
];

// Property map: 'text-color' → { target: 'text', prop: 'color' }
const PREFIX_MAP = {
  'text-color': ['text', 'color'],
  'text-glow': ['text', 'glow'],
  'text-blur': ['text', 'blur'],
  'text-animate': ['text', 'animate'],
  'text-speed': ['text', 'speed'],
  'text-dashed': ['text', 'dashed'],
  'svg-color': ['svg', 'color'],
  'svg-glow': ['svg', 'glow'],
  'svg-blur': ['svg', 'blur'],
  'svg-animate': ['svg', 'animate'],
  'svg-speed': ['svg', 'speed'],
  'svg-dashed': ['svg', 'dashed'],
  'svg-stroke-width': ['svg', 'svgStrokeWidth'],
  'svg-broken-ratio': ['svg', 'brokenRatio'],
};

// Read attribute value from element, fall through cascade chain
function readAttr(el, name) {
  return el.getAttribute(name);
}

function resolveConfig(el, contentType) {
  const get = (prop) => {
    if (contentType !== 'host') {
      const prefixed = `${contentType}-${prop}`;
      const val = readAttr(el, prefixed);
      if (val !== null) return val;
    }
    const val = readAttr(el, prop);
    if (val !== null) return val;
    return DEFAULTS[prop];
  };

  return {
    color: get('color'),
    glow: parseNumber(get('glow'), DEFAULTS.glow),
    blur: parseNumber(get('blur'), DEFAULTS.blur),
    animate: get('animate'),
    speed: parseNumber(get('speed'), DEFAULTS.speed),
    dashed: parseBoolean(get('dashed')),
    fontFamily: get('fontFamily'),
    fontSize: parseNumber(get('fontSize'), DEFAULTS.fontSize),
    fontWeight: get('fontWeight'),
    fontStyle: get('fontStyle'),
    textTransform: get('textTransform'),
    letterSpacing: parseNumber(get('letterSpacing'), DEFAULTS.letterSpacing),
    svgStrokeWidth: parseNumber(get('svgStrokeWidth'), DEFAULTS.svgStrokeWidth),
    // Read kebab-case attribute directly (get() uses camelCase and won't match kebab attr)
    brokenRatio: parseNumber(
      readAttr(el, contentType !== 'host' ? `${contentType}-broken-ratio` : null) ||
      readAttr(el, 'broken-ratio') ||
      DEFAULTS.brokenRatio, DEFAULTS.brokenRatio),
  };
}

function resolveHostConfig(el) {
  return resolveConfig(el, 'host');
}

function resolveTextConfig(el) {
  return resolveConfig(el, 'text');
}

function resolveSvgConfig(el) {
  return resolveConfig(el, 'svg');
}

/* ===== src/animations.js ===== */
function generateFlicker(speed) {
  const dur = (6 / speed).toFixed(2);
  return `
    @keyframes neon-flicker {
      0%, 13%, 26%, 37%, 58%, 77%, 100% { opacity: 1; }
      5%, 20%, 30%, 50%, 69%, 90%      { opacity: 0.25; }
    }
    @keyframes neon-flicker-glow {
      0%, 15%, 28%, 39%, 56%, 75%, 100% { opacity: 0.7; }
      7%, 22%, 32%, 48%, 66%, 88%       { opacity: 0.15; }
    }
    .neon-front { animation: neon-flicker ${dur}s infinite step-end; }
    .neon-back  { animation: neon-flicker-glow ${dur}s infinite 0.15s step-end; }
  `;
}

function generateBreath(speed) {
  const dur = (4 / speed).toFixed(2);
  return `
    @keyframes neon-breath {
      0%, 100% { opacity: 1; }
      50%      { opacity: 0.35; }
    }
    @keyframes neon-breath-glow {
      0%, 100% { opacity: 0.75; }
      50%      { opacity: 0.2; }
    }
    .neon-front { animation: neon-breath ${dur}s infinite ease-in-out; }
    .neon-back  { animation: neon-breath-glow ${dur}s infinite 0.2s ease-in-out; }
  `;
}

function generateGlitch(speed) {
  const dur = (3 / speed).toFixed(2);
  return `
    @keyframes neon-glitch {
      0%, 15%, 55%, 85%          { opacity: 1; }
      8%, 23%, 48%, 75%, 92%     { opacity: 0.1; }
      35%, 67%                   { opacity: 0.7; }
    }
    @keyframes neon-glitch-color {
      0%, 15%, 55%, 85%          { stroke: inherit; }
      8%, 48%, 92%               { stroke: #fff; }
      23%, 75%                   { stroke: gold; }
      35%, 67%                   { stroke: currentColor; }
    }
    @keyframes neon-glitch-glow {
      0%, 17%, 53%, 82%          { opacity: 0.6; }
      10%, 25%, 50%, 72%, 90%    { opacity: 0.1; }
      38%, 65%                   { opacity: 0.4; }
    }
    .neon-front { animation: neon-glitch ${dur}s infinite step-end, neon-glitch-color ${dur}s infinite step-end; }
    .neon-back  { animation: neon-glitch-glow ${dur}s infinite 0.08s step-end; }
  `;
}

function generateBroken(speed) {
  const dur = (4 / speed).toFixed(2);
  return `
    @keyframes neon-broken-flicker {
      0%, 100% { opacity: 0.55; }
      18%, 33%, 68% { opacity: 0.15; }
      25%, 51%, 82% { opacity: 0.75; }
      43%, 91% { opacity: 0.08; }
    }
    @keyframes neon-broken-glow {
      0%, 100% { opacity: 0.6; }
      18%, 33%, 68% { opacity: 0.25; }
      25%, 51%, 82% { opacity: 0.8; }
      43%, 91% { opacity: 0.12; }
    }
    .neon-svg-broken-dim { animation: neon-broken-flicker ${dur}s infinite step-end; }
    .neon-svg-broken-glow { animation: neon-broken-glow ${dur}s infinite 0.15s step-end; }
  `;
}

function generateFlow(speed) {
  const dur = (2.5 / speed).toFixed(2);
  return `
    @keyframes neon-flow-march {
      0%   { stroke-dashoffset: var(--flow-total); }
      100% { stroke-dashoffset: 0; }
    }
    .neon-svg-flow {
      animation: neon-flow-march ${dur}s infinite linear;
    }
  `;
}

const ANIMATION_GENERATORS = {
  flicker: generateFlicker,
  breath: generateBreath,
  glitch: generateGlitch,
  broken: generateBroken,
  flow: generateFlow,
};

function generateAnimationStyle(animateName, speed) {
  if (!animateName || animateName === 'none') return '';
  const gen = ANIMATION_GENERATORS[animateName];
  return gen ? gen(speed) : '';
}

/* ===== src/renderer.js ===== */
const GAP = 16;

function renderLightDom(el, width, height) {
  const textCfg = resolveTextConfig(el);
  const svgCfg = resolveSvgConfig(el);
  const backGroup = createSvgElement('g', { class: 'neon-back' });
  const frontGroup = createSvgElement('g', { class: 'neon-front' });

  // Separate text and SVG items from light DOM
  const textParts = [];
  const svgParts = [];
  for (const child of el.childNodes) {
    if (child.nodeType === Node.TEXT_NODE) {
      const t = child.textContent.trim();
      if (t) textParts.push(t);
    } else if (child.nodeType === Node.ELEMENT_NODE && child.tagName.toLowerCase() === 'svg') {
      svgParts.push(child);
    }
  }

  const hasText = textParts.length > 0;
  const hasSvg = svgParts.length > 0;
  const fullText = textParts.join(' ');
  const y = height * 0.62;

  if (hasText && hasSvg) {
    // Text centered in left portion, SVGs to its right
    // Estimate text width for positioning
    const textW = estimateTextPx(fullText, textCfg.fontSize);
    const svgTotalW = svgParts.reduce((s, svg) => s + (parseFloat(svg.getAttribute('width')) || 64), 0)
      + Math.max(0, svgParts.length - 1) * GAP;
    const totalW = textW + GAP + svgTotalW;
    const startX = (width - totalW) / 2;

    // Text at left portion
    appendTextLayers(backGroup, frontGroup, fullText, textCfg, startX + textW / 2, y, startX);

    // SVGs to the right
    let sx = startX + textW + GAP;
    for (const svg of svgParts) {
      const sw = parseFloat(svg.getAttribute('width')) || 64;
      appendSvgShapes(backGroup, frontGroup, svg, svgCfg, sx, y);
      sx += sw + GAP;
    }
  } else if (hasText) {
    // Text only: center in SVG
    appendTextLayers(backGroup, frontGroup, fullText, textCfg, width / 2, y, 0);
  } else if (hasSvg) {
    // SVG only: center all SVGs
    const svgTotalW = svgParts.reduce((s, svg) => s + (parseFloat(svg.getAttribute('width')) || 64), 0)
      + Math.max(0, svgParts.length - 1) * GAP;
    let sx = (width - svgTotalW) / 2;
    for (const svg of svgParts) {
      const sw = parseFloat(svg.getAttribute('width')) || 64;
      appendSvgShapes(backGroup, frontGroup, svg, svgCfg, sx, y);
      sx += sw + GAP;
    }
  }

  return { backGroup, frontGroup };
}

// Rough pixel width estimate — kept generous to avoid clipping
function estimateTextPx(text, fontSize) {
  let n = 0;
  for (const ch of text) {
    n += /[一-鿿　-〿＀-￯]/.test(ch) ? 1.1 : 0.7;
  }
  return Math.ceil(n * fontSize);
}

function appendTextLayers(backGroup, frontGroup, text, cfg, cx, y, /* optional for dash bleed */ _unused) {
  const base = {
    'font-family': cfg.fontFamily,
    'font-size': `${cfg.fontSize}px`,
    'font-weight': cfg.fontWeight,
    'font-style': cfg.fontStyle,
    'text-transform': cfg.textTransform,
    'letter-spacing': `${cfg.letterSpacing}px`,
    fill: cfg.color,
    'fill-opacity': '0.4',
    'text-anchor': 'middle',
    x: String(cx),
    y: String(y),
  };
  const dash = cfg.dashed ? { 'stroke-dasharray': '180 100' } : {};

  const backText = createSvgElement('text', {
    ...base,
    stroke: cfg.color,
    'stroke-width': cfg.glow,
    filter: 'url(#neon-blur)',
    ...dash,
  });
  backText.textContent = text;
  backGroup.appendChild(backText);

  const frontText = createSvgElement('text', {
    ...base,
    stroke: cfg.color,
    'stroke-width': 2,
    ...dash,
  });
  frontText.textContent = text;
  frontGroup.appendChild(frontText);
}

function appendSvgShapes(backGroup, frontGroup, sourceSvg, cfg, x, y) {
  const shapes = Array.from(sourceSvg.querySelectorAll('path, circle, rect, ellipse, line, polyline, polygon'));
  if (shapes.length === 0) return;

  // Compute scale so the shapes render at the inline SVG's declared size
  const vbox = sourceSvg.getAttribute('viewBox') || '0 0 24 24';
  const vbParts = vbox.split(/\s+/).map(Number);
  const vbW = vbParts[2] || 24;
  const vbH = vbParts[3] || 24;
  const sw = parseFloat(sourceSvg.getAttribute('width')) || 64;
  const sh = parseFloat(sourceSvg.getAttribute('height')) || 64;
  const sx = sw / vbW;
  const sy = sh / vbH;
  const ty = y - (sh / 2);
  const fill = shapes[0] ? (shapes[0].getAttribute('fill') || 'none') : 'none';

  if (cfg.animate === 'broken') {
    const host = sourceSvg.closest('neon-light');
    const pathCfg = parsePathConfig(host ? host.getAttribute('path-config') : null);
    const ratio = getBrokenRatio(host, cfg);
    const { normalShapes, brokenShapes } = classifyShapes(shapes, pathCfg, ratio);
    if (normalShapes.length > 0) {
      renderGroupedShapes(backGroup, normalShapes, cfg, x, ty, sx, sy, { fill, blur: true });
      renderGroupedShapes(frontGroup, normalShapes, cfg, x, ty, sx, sy, { fill });
    }
    if (brokenShapes.length > 0) {
      renderGroupedShapes(backGroup, brokenShapes, cfg, x, ty, sx, sy, {
        fill: 'none', blur: true, class: 'neon-svg-broken-glow',
      });
      renderGroupedShapes(frontGroup, brokenShapes, cfg, x, ty, sx, sy, {
        fill: 'none', class: 'neon-svg-broken-dim',
      });
    }
    return;
  }

  const dash = cfg.dashed ? { 'stroke-dasharray': '180 100' } : {};
  const frontStyle = cfg.animate === 'flow' ? 'opacity:0.3' : '';

  // Apply per-path color overrides from path-config if present
  const host = sourceSvg.closest('neon-light');
  const pathCfg = parsePathConfig(host ? host.getAttribute('path-config') : null);
  if (pathCfg.size > 0) {
    for (const shape of shapes) {
      const sid = shape.getAttribute('id') || shape.getAttribute('p-id');
      const override = sid ? pathCfg.get(sid) : null;
      shape._effColor = (override && override.color) ? override.color : null;
    }
  }

  if (cfg.animate === 'flow') {
    addShapeLayer(backGroup, shapes, cfg, x, ty, sx, sy, { fill: 'none', blur: true, dash });
    addShapeLayer(frontGroup, shapes, cfg, x, ty, sx, sy, { fill, style: frontStyle, dash });
  } else {
    renderGroupedShapes(backGroup, shapes, cfg, x, ty, sx, sy, { fill: 'none', blur: true, dash });
    renderGroupedShapes(frontGroup, shapes, cfg, x, ty, sx, sy, { fill, style: frontStyle, dash });
  }

  if (cfg.animate === 'flow') {
    appendFlowLayers(frontGroup, shapes, cfg, x, ty, sx, sy, Math.max(vbW, vbH));
  }
}

// Parse path-config attribute: "id1: color:#fff, broken:true; id2: color:#f00"
function parsePathConfig(str) {
  const map = new Map();
  if (!str) return map;
  for (const block of str.split(';')) {
    const idx = block.indexOf(':');
    if (idx === -1) continue;
    const id = block.substring(0, idx).trim();
    const rest = block.substring(idx + 1).trim();
    if (!id || !rest) continue;
    const props = {};
    for (const pair of rest.split(',')) {
      const pidx = pair.indexOf(':');
      if (pidx === -1) continue;
      const k = pair.substring(0, pidx).trim();
      const v = pair.substring(pidx + 1).trim();
      if (k) props[k] = v;
    }
    if (Object.keys(props).length > 0) map.set(id, props);
  }
  return map;
}

function getBrokenRatio(host, cfg) {
  if (!host) return cfg.brokenRatio || 0.5;
  const raw = host.getAttribute('svg-broken-ratio') || host.getAttribute('broken-ratio');
  return raw ? Math.max(0, Math.min(1, parseFloat(raw))) : (cfg.brokenRatio || 0.5);
}

// Classify shapes into normal/broken, considering per-path overrides and global ratio
function classifyShapes(shapes, pathCfg, ratio) {
  const forceBroken = [];
  const forceNormal = [];
  const autoShapes = [];

  for (const shape of shapes) {
    const sid = shape.getAttribute('id') || shape.getAttribute('p-id');
    const override = sid ? pathCfg.get(sid) : null;
    shape._effColor = (override && override.color) ? override.color : null;

    if (override && 'broken' in override) {
      if (override.broken === 'true' || override.broken === '1') forceBroken.push(shape);
      else forceNormal.push(shape);
    } else {
      autoShapes.push(shape);
    }
  }

  const targetBroken = Math.round(shapes.length * ratio);
  const needed = Math.max(0, targetBroken - forceBroken.length);
  const clamped = Math.min(needed, autoShapes.length);

  const autoBrokenSet = new Set();
  if (clamped > 0 && autoShapes.length > 0) {
    const hashed = autoShapes.map((s, i) => {
      const str = s.getAttribute('d') || s.getAttribute('points') || s.getAttribute('cx') || s.outerHTML;
      let h = 0;
      for (let j = 0; j < str.length; j++) { h = ((h << 5) - h) + str.charCodeAt(j); h |= 0; }
      return { idx: i, hash: Math.abs(h) };
    });
    hashed.sort((a, b) => a.hash - b.hash);
    for (const item of hashed.slice(0, clamped)) autoBrokenSet.add(item.idx);
  }

  const normalShapes = [...forceNormal];
  const brokenShapes = [...forceBroken];
  for (let i = 0; i < autoShapes.length; i++) {
    if (autoBrokenSet.has(i)) brokenShapes.push(autoShapes[i]);
    else normalShapes.push(autoShapes[i]);
  }
  return { normalShapes, brokenShapes };
}

// Group shapes by effective color and render each group
function renderGroupedShapes(parent, shapes, cfg, x, ty, sx, sy, opts) {
  const groups = new Map();
  for (const shape of shapes) {
    const c = shape._effColor || cfg.color;
    if (!groups.has(c)) groups.set(c, []);
    groups.get(c).push(shape);
  }
  for (const [color, groupShapes] of groups) {
    addShapeLayer(parent, groupShapes, cfg, x, ty, sx, sy, { ...opts, color });
  }
}

function addShapeLayer(parent, shapes, cfg, x, ty, sx, sy, opts) {
  const attrs = {
    transform: `translate(${x}, ${ty}) scale(${sx}, ${sy})`,
    fill: opts.fill || 'none',
    stroke: opts.color || cfg.color,
    'stroke-width': String(opts.blur ? cfg.glow : Math.max(1, cfg.svgStrokeWidth)),
    ...(opts.filter || (opts.blur ? 'url(#neon-blur)' : '')),
    ...(opts.class ? { class: opts.class } : {}),
    ...(opts.style ? { style: opts.style } : {}),
    ...(opts.dash || {}),
  };
  if (!attrs.filter) delete attrs.filter;
  const g = createSvgElement('g', attrs);
  for (const shape of shapes) g.appendChild(cloneShape(shape));
  parent.appendChild(g);
}

function appendFlowLayers(frontGroup, shapes, cfg, x, ty, sx, sy, dashBase) {
  const flowDash = dashBase * 0.15;
  const flowGap = dashBase * 3;
  const flowTotal = flowDash + flowGap;
  const dashFlow = { 'stroke-dasharray': `${flowDash} ${flowGap}` };
  const delays = ['0s', `-${(0.8 / cfg.speed).toFixed(2)}s`, `-${(1.6 / cfg.speed).toFixed(2)}s`];
  // 3 chasing light layers at different brightness
  const layers = [
    { opacity: 1, delay: delays[0] },
    { opacity: 0.55, delay: delays[1] },
    { opacity: 0.25, delay: delays[2] },
  ];
  for (const layer of layers) {
    const g = createSvgElement('g', {
      transform: `translate(${x}, ${ty}) scale(${sx}, ${sy})`,
      fill: 'none',
      stroke: cfg.color,
      'stroke-width': String(Math.max(1, cfg.svgStrokeWidth)),
      class: 'neon-svg-flow',
      style: `--flow-total:${flowTotal};opacity:${layer.opacity};animation-delay:${layer.delay}`,
      ...dashFlow,
    });
    for (const shape of shapes) {
      g.appendChild(cloneShape(shape));
    }
    frontGroup.appendChild(g);
  }
}

function cloneShape(shape) {
  const el = createSvgElement(shape.tagName);
  for (const { name, value } of shape.attributes) {
    if (name === 'fill' || name === 'stroke') continue;
    el.setAttribute(name, value);
  }
  return el;
}

function buildSvgSurface(hostWidth, hostHeight) {
  return createSvgElement('svg', {
    class: 'neon-surface',
    width: '100%',
    height: '100%',
    viewBox: `0 0 ${hostWidth} ${hostHeight}`,
    preserveAspectRatio: 'xMidYMid meet',
  });
}

function buildDefs(blurAmount) {
  const defs = createSvgElement('defs');
  const filter = createSvgElement('filter', { id: 'neon-blur' });
  const blur = createSvgElement('feGaussianBlur', {
    in: 'SourceGraphic',
    stdDeviation: String(blurAmount),
  });
  filter.appendChild(blur);
  defs.appendChild(filter);
  return defs;
}

/* ===== src/neon-light.js ===== */
const BASE_STYLES = `
  :host {
    display: inline-block;
    position: relative;
    overflow: hidden;
    box-sizing: border-box;
  }
  :host([hidden]) { display: none; }
  svg.neon-surface {
    display: block;
    width: 100%;
    height: 100%;
  }
  .neon-back {
    opacity: var(--neon-back-opacity, 0.6);
  }
  .neon-front {
    opacity: var(--neon-front-opacity, 1);
  }
`;

class NeonLight extends HTMLElement {
  static observedAttributes = OBSERVED_ATTRS;

  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this._observer = null;
    this._mutObserver = null;
    this._svg = null;
  }

  connectedCallback() {
    this._render();
    this._startObserver();
    this._startMutationObserver();
  }

  disconnectedCallback() {
    if (this._observer) {
      this._observer.disconnect();
      this._observer = null;
    }
    if (this._mutObserver) {
      this._mutObserver.disconnect();
      this._mutObserver = null;
    }
  }

  attributeChangedCallback(name, oldVal, newVal) {
    if (oldVal !== newVal && this._svg) {
      this._render();
    }
  }

  _render() {
    const cfg = resolveHostConfig(this);
    const rect = this.getBoundingClientRect();
    const width = rect.width || 600;
    const height = rect.height || 150;

    // Bridge config values to CSS custom properties (user style attr takes precedence)
    this._syncCssProps(cfg);

    // Build SVG surface
    this._svg = buildSvgSurface(width, height);
    const defs = buildDefs(cfg.blur);
    this._svg.appendChild(defs);

    // Render light DOM content into dual layers
    const { backGroup, frontGroup } = renderLightDom(this, width, height);
    this._svg.appendChild(backGroup);
    this._svg.appendChild(frontGroup);

    // Inject animation styles — merge host, text, and svg animation configs
    const textCfg = resolveTextConfig(this);
    const svgCfg = resolveSvgConfig(this);
    const animCSS = generateAnimationStyle(cfg.animate, cfg.speed)
      + generateAnimationStyle(textCfg.animate, textCfg.speed)
      + generateAnimationStyle(svgCfg.animate, svgCfg.speed);
    const styleEl = document.createElement('style');
    styleEl.textContent = BASE_STYLES + animCSS;

    // Replace shadow content
    this.shadowRoot.innerHTML = '';
    this.shadowRoot.appendChild(styleEl);
    this.shadowRoot.appendChild(this._svg);
  }

  _syncCssProps(cfg) {
    // Only set a custom property if the user hasn't explicitly set it via style attr
    const sync = (name, value) => {
      if (!this.style.getPropertyValue(name)) {
        this.style.setProperty(name, value);
      }
    };
    sync('--neon-color', cfg.color);
    sync('--neon-blur-amount', String(cfg.blur));
    sync('--neon-stroke-width', String(cfg.svgStrokeWidth));
    sync('--neon-dash-length', '180');
    sync('--neon-dash-gap', '100');
  }

  _startObserver() {
    if (this._observer) return;
    this._observer = new ResizeObserver(() => {
      if (this._svg) this._render();
    });
    this._observer.observe(this);
  }

  _startMutationObserver() {
    if (this._mutObserver) return;
    this._mutObserver = new MutationObserver(() => {
      if (this._svg) this._render();
    });
    this._mutObserver.observe(this, { childList: true });
  }
}

/* ===== src/index.js ===== */
function define(name = 'neon-light', element = NeonLight) {
  if (typeof customElements !== 'undefined' && !customElements.get(name)) {
    customElements.define(name, element);
  }
}

define();

export { NeonLight, define };
